name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  # push:
  #   branches: ["main", "next"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commitlint:
    name: 🔬 Commitlint
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/pnpm-setup
        name: Setup pnpm
      - name: Install commitlint
        run: |
          pnpm install conventional-changelog-conventionalcommits
          pnpm install commitlint@latest

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  eslint:
    name: 🔬 ESLint
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: ./.github/actions/pnpm-setup
        name: Setup pnpm

      - name: Task
        run: 'pnpm run lint:eslint'

      - name: Upload ESLint report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: |
            apps/membership-ui/eslint-report.json

  tsc:
    name: 🔬 Typescript Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/cache@v3
        name: Restore tsconfig.tsbuildinfo cache
        with:
          path: ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: ${{ runner.os }}-tsbuildinfo-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-tsbuildinfo-

      - uses: ./.github/actions/pnpm-setup
        name: Setup pnpm

      - name: Task
        run: 'pnpm run lint:tsc'

  ts-coverage:
    name: 🔬 Typescript Coverage
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: ./.github/actions/pnpm-setup
        name: Setup pnpm

      - name: Task
        run: 'pnpm run lint:ts-coverage'
